### ISSUE TITLE
[Feature Request] Migrate to read_only possible?

### ISSUE THREAD

**Issue by OdinVex** [MeCJay12/lsi-storage-authority#4]
I'm not sure if LSISA can be worked with to relocate where it can get authentication and write logs to but I'd like to hopefully be able to set `read_only` on this Docker in the future. Prevents root-fs writing, just another security measure. Same with a healthcheck.

Currently using this healthcheck:

```
healthcheck:
  test: wget -q --spider http://localhost:2463 || exit 1
  interval: 60s
  retries: 3
  start_period: 60s
  timeout: 10s
```
